# Generated by Django 3.1 on 2020-10-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='confirmed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='recovered',
            field=models.IntegerField(null=True),
        ),
    ]
