# Generated by Django 3.1 on 2020-10-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='title',
        ),
    ]
